### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by Xottab-DUTY**
19 line is correct? I mean my comment there. It won't break anything?)

### CODE REVIEW

**Comment by Keridos** [comment]
take a look here: https://github.com/Keridos/FloodLights/blob/master/src/main/resources/assets/floodlights/lang/en_US.lang#L14

**Comment by Xottab-DUTY** [comment]
Looked. What was I supposed to see? :D

**Comment by Keridos** [comment]
nvm, I derped

**Comment by Xottab-DUTY** [comment]
Ok :D

**Pull request merged**
